name: Deploy to Production

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.dev.*"
      - "**/docker-compose.dev.yml"
      - "**/Dockerfile.dev"
      - "**/nginx.dev.conf"
      - "**/.env.dev"
      - "pgdata/**"
      - "**/*.test.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # -------------------------------------
      #  Login to Docker Hub
      # -------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------------------
      #  FRONTEND BUILD + PUSH
      # -------------------------------------
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: pipinovi4/frontend-production:latest
          no-cache: true
          build-args: |
            NEXT_PUBLIC_API_URL=https://worldflowcredit.com

      # -------------------------------------
      #  BACKEND BUILD + PUSH
      # -------------------------------------
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: pipinovi4/backend-production:latest
          no-cache: true

      # -------------------------------------
      #  UPLOAD UPDATED FILES TO VPS
      # -------------------------------------
      - name: Upload docker-compose.prod.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/opt/Fincontrol"
          overwrite: true

      # -------------------------------------
      #  DEPLOY ON VPS
      # -------------------------------------
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/Fincontrol
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker system prune -f
            echo "âœ… Deploy completed"
